language: python
python:
- "3.7"

install:
- pip install .
- pip install -r requirements-test.txt

script:
- coverage run -m pytest
- coverage report -m

deploy:
- provider: pypi
  username: __token__
  server: https://test.pypi.org/legacy/
  password:
    secure: x7+t0omF3y5EwbPgqFmv1EkqqVh7MRflbOAUk2IIyFFKdQnGn8qyDqWMtwvZhxYvjrxlmite3qK9crO7HVlrO8TYyUlLCs4JfNJiKTbMYFgjXLOYUtjRA5jn0ycVqO0gTzjQGwzjVraDFCZwmQYGQfKz3FXl+6lXaALeZYBIb4a7BGqvOGOJT6oyjphYjuYtpF14oQXJTZYgWBAKcnhTWtL0clcLehZgm5oQIwCQq7tVNCwaQoodAQi9cDmOihgevxDiDw2LU/VYWTzig8xUgdKOc+9XNLiV1uvPd8b9eKmSP/29WVZBcxKC4ePkCsKtOKy9J/KTCWixkiPo3GEu0klLr/EnqW5+GjEDZR5gPwgYPi6D8xQ4MVRBlQrUIQgsJfnhgAM2Efxej5KZ317a9eVipMW/ZQelSfTg4zBa3RzkPPfBjum1VNyrpph0uHOQSnk0108FmNA+M/mc2KeQsSfjYaYymel9AvtOlZ0TKt1peckPNW4Pg+gR1Bo8fbYNLNpCcXcOQrj/95xDYLRDioJmqaV1S1Ya/VzCy2KycMnXM1zGOfHaUNZ1TLva3N10Cfs6zMqmpukmm++dBaJ7uJTZuEzBNa24vsM2V+9l3dLqMu3os/f90bdO720+INgcP0Jz0U/8OV8MVZRCVydMNVSfdOUYXobiiAFwkthr+8w=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?-test(\.[0-9]+)?$
- provider: pypi
  username: __token__
  password:
    secure: LTYWITkTLt0OzqLgABqQdFrXCFu3bbfLC2kyLgKOcdsF4QMTcqWk+9LUtAQMDVsoB8MfXxTcFzD5NfZEtODsSP/PSCa18+uTlxBSXx6RoHxqkna+4VHngC7etkeTZipx90gxgss7ymaWAwwXIN4AZgTme4j6Wft8kTmi0T4C3SGYd/P1eLFWia5BXtFu9JHKC8Mb4IvG3z6itPAo1ZQ1/73aTKEOHrXkOU3r3b2O0peNzw+fM1alx69m/63yePG7n+X7vXLFe/sblu8FBi8pArc0qNhru4fueUYhmJlx13hxNcqmjKEdTUVRHPnd2fT2ds2yzBwUjwzXGa4UTHYookZB9VEgDxFv2LTFNcns+o9LTcsS6pkUkRfM+TR8jVCaRPb147+jhpmNNRkPD89VMG2pjWhW0RoTjMs91LfQVcmkNf+184SjNFDdqgkgPR6cs4fyKjDBSNzSmkKyrBmU2OIexBxW/ao7RU/Io01zJwgEzAP7SlKCZNE0o0zMLTqtw1Snk27sFNTWwpIxcdnNtqr/bE5myRm5Y5wm4TYCGnM2K7unFjlReq8DwvdH6PwhQB6HM2OZ4Wbk7tAcXL8aPulSyc3IH05iA2w9CFOddM8wrHbFxZUyBNuB6yufZ0DqgpE6VsZvgUH89PXWwmXkJBJ5LdZFoudCJ+6oe/90H6o=
  on:
    tags: true
    repo: Ensembl/ensembl-prodinf-core
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$