language: python
dist: jammy
python:
- "3.10"

install:
- pip install .
- pip install -r requirements-test.txt
- export PYTHONPATH=$PYTHONPATH:$PWD/src

script:
- coverage run -m pytest src/tests
- coverage report -m
