language: python
python:
- "3.7"

install:
- pip install .
- pip install -r requirements-test.txt

script:
- coverage run -m pytest
- coverage report -m

deploy:
- provider: pypi
  username: __token__
  server: https://test.pypi.org/legacy/
  password:
    secure: dG2OpxwMSj6hCHV9aTjcr588txBEQf61Pv8BfrMsjQp8JwFMpEefd/L5FuxaYljw51Q4s6FRlnb1ouQn1O2O8fypJwUM5tFtkgi/jD3jdxi4xRgMB34COpefncu2JMNukEKII+PS1aA58oC9hBd6gz5ww3a04PR+aG+ODLRtdPuMIvr10oa85tr3q7crQOiE5oEgZ2vIuR/SD2oLKjNvoft1agi+urwbB7IFr0gKJPoxN5x4BXmUpTGeXl282oElXg6eG+vuVI0rjDxumtjraMCPpsxBjq8Ne0jWMLZ0JSsT5MFxc0Qi04OFBpI/LvhQQuOCsqPXO2qgZC2FlWTuzTaLPZBx5FI5l1nKmLDeQr2g02vq1Wnm880CFXdC9oe/JqIfUEUrRgP65d2Lp10OOzsu8SUv7bg+G39oKDShsGfAcki096l7xXx1W6GoIpCf5jU85+XgqKjqCacUKewPr1MuYJ1iX6qbgLNvzF4nlt+dx2zNK7IX06Lr3Enc+QoI+TSEzPnM+3IgQR0pkUSKZJKgZPGnHbDChHdfn4hPU+QvfjOsMs9hVLQ6X4vEPsaAC3rAM6kb1JHh2yxGqyNc0z386RKXtaqG4wPF4ppg+q361CirogLK82Z9IeySE1ugavrpIQsN5ZXJ3CTs2CYks75z74SHK/+ro4vSCJPxjyQ=
  on:
    tags: true
    repo: Ensembl/ensembl-prodinf-core
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?-test(\.[0-9]+)?$
- provider: pypi
  username: __token__
  password:
    secure: MesZa1qYpw3LsKrt38VXfzHOqDkMlAtNhyEi/ZjQzC614a7LeSeWcLhjCEloU40Z3D3mw4eE/I6yKnPOdNzPn7yXar8xX5mebWLEiEjiF+zMgDBJj8U+jil3cQylWgRbV5lCSUJ0SyGxngPfIlf2WCTwI1CSV2BklaVPZEaSakBCScn9ehVE9I5/NEOtG6IZG94weqm4vIWXZuzULhx5gk992+KzIB90auBzDQKY/hcKQ7hOEoiDxGelt6auohl1QoICeuN1Xqz393tbkByKNyccQm8XDFYzgbsN9uHGOn+yoPHmTKPMWIj0jrlYJpPezI7Y4Ev6iU7+S00+2XFqWSXTwi1W4JroZuVI4ZteN9H/XjAZJ9u7PZDoZpn55VKYHocLoA+//8xwli4M6l2XYLOSvgOFxlyl2/l27G/IxkYSAGMooRpWHriEVRSMXpf9/emJFjWSl0NKoG7C/5lWLx/S5fxo1654Qa91wp0+7jPAtY9RtzoS+y3gvh1IEXK4JtCDtGGovm58c1lMCa3RDebD6G2dEy9hJm/WA+cS3VSnIRiFNXDJWM9aVOza84T29bPTLHS7hLeyWbcN9Vr6I8P/Vu2v5RKDUZlfcNW6Z08kmNH9OhRYgajYAGgQSdz6619bfIXUXtNAbelYWk9P3TDTy/aRIhaQmHmWCefOkeA=
  on:
    tags: true
    repo: Ensembl/ensembl-prodinf-core
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$