#openapi: "3.0.2"

info:
  title: "GIFTs"
  version: "1.0"

tags:
  - name: Update, process, and publish GIFTs data

paths:
  /gifts/update_ensembl:
    post:
      tags:
        - Update Ensembl data in the GIFTs database
      summary: "Load Ensembl data into the GIFTs database"
      responses:
        200:
          description: ID of submitted job in hive database.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/result"
    get:
      tags:
        - Update Ensembl data in the GIFTs database
      summary: "Retrieve information for all Ensembl updates to the GIFTs database"
      responses:
        200:
          description: Details of 'Update Ensembl' jobs.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs"

  /gifts/update_ensembl/{job_id}:
    get:
      tags:
        - Update Ensembl data in the GIFTs database
      summary: "Retrieve information for a specific Ensembl update to the GIFTs database"
      parameters:
        - $ref: "#/components/parameters/job"
      responses:
        200:
          description: Details of the specified 'Update Ensembl' job.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"

  /gifts/update_ensembl/status/{ensembl_release}:
    get:
      tags:
        - Update Ensembl data in the GIFTs database
      summary: "Retrieve the status of the Ensembl update to the GIFTs database for a given release"
      parameters:
        - $ref: "#/components/parameters/ensembl_release"
      responses:
        200:
          description: Status of the latest 'Update Ensembl' job for the specified release.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"

  /gifts/process_mapping:
    post:
      tags:
        - Update Ensembl and UniProt alignments in the GIFTs database
      summary: "Align Ensembl and UniProt data"
      responses:
        200:
          description: ID of submitted job in hive database.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/result"
    get:
      tags:
        - Update Ensembl and UniProt alignments in the GIFTs database
      summary: "Retrieve information for all updates to the Ensembl and UniProt alignments"
      responses:
        200:
          description: Details of 'Process Mapping' jobs.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs"

  /gifts/process_mapping/{job_id}:
    get:
      tags:
        - Update Ensembl and UniProt alignments in the GIFTs database
      summary: "Retrieve information for a specific update to the Ensembl and UniProt alignments"
      parameters:
        - $ref: "#/components/parameters/job"
      responses:
        200:
          description: Details of the specified 'Process Mapping' job.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"

  /gifts/process_mapping/status/{ensembl_release}:
    get:
      tags:
        - Update Ensembl and UniProt alignments in the GIFTs database
      summary: "Retrieve the status of the update to the Ensembl and UniProt alignments for a given release"
      parameters:
        - $ref: "#/components/parameters/ensembl_release"
      responses:
        200:
          description: Status of the latest 'Process Mapping' job for the specified release.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"

  /gifts/publish_mapping:
    post:
      tags:
        - Publish GIFTs database with latest Ensembl/UniProt alignments
      summary: "Publish latest GIFTs data"
      responses:
        200:
          description: ID of submission job in hive database.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/result"
    get:
      tags:
        - Publish GIFTs database with latest Ensembl/UniProt alignments
      summary: "Retrieve information for all publications of GIFTs data"
      responses:
        200:
          description: Details of 'Publish Mapping' jobs.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/jobs"

  /gifts/publish_mapping/{job_id}:
    get:
      tags:
        - Publish GIFTs database with latest Ensembl/UniProt alignments
      summary: "Retrieve information for a specific publication of GIFTs data"
      parameters:
        - $ref: "#/components/parameters/job"
      responses:
        200:
          description: Details of the specified 'Publish Mapping' job.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"

  /gifts/publish_mapping/status/{ensembl_release}:
    get:
      tags:
        - Publish GIFTs database with latest Ensembl/UniProt alignments
      summary: "Retrieve the status of the publication of GIFTs data for a given release"
      parameters:
        - $ref: "#/components/parameters/ensembl_release"
      responses:
        200:
          description: Status of the latest 'Publish Mapping' job for the specified release.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/status"

components:
  parameters:
    job_id:
      name: job_id
      in: path
      description: ID for a submission job in hive database
      required: true
      schema:
        type: integer
        example: 1

    ensembl_release:
      name: ensembl_release
      in: path
      description: An Ensembl release
      required: true
      schema:
        type: integer
        example: 99

  schemas:
    result:
      title: result
      type: object
      properties:
        job_id:
          type: integer
          description: ID for a submission job in hive database
          example: 1

    job:
      title: job
      type: object
      properties:
        job_id:
          type: integer
          description: ID for a submission job in hive database
          example: 1

    jobs:
      title: jobs
      type: object
      properties:
        group:
          type: array
          items:
            $ref: "#/components/schemas/job"

    status:
      title: status
      type: object
      properties:
        status:
          type: string
          description: Status of a GIFTs pipeline
          example: 'running'
